export const FETCH_MOVIES_START         = 'FETCH_MOVIES_START';
export const FETCH_NOW_PLAYING_MOVIES   = 'FETCH_NOW_PLAYING_MOVIES';
export const FETCH_NOW_PLAYING_SUCCESS  = 'FETCH_NOW_PLAYING_SUCCESS';
export const FETCH_NOW_PLAYING_FAIL     = 'FETCH_NOW_PLAYING_FAIL';

export const CHANGE_CAROUSEL_MOVIE        = 'CHANGE_CAROUSEL_MOVIE';
export const CHANGE_CAROUSEL_MOVIE_ARROW  = 'CHANGE_CAROUSEL_MOVIE_ARROW';

export const RESIZE_CAROUSEL_SLIDE      = 'RESIZE_CAROUSEL_SLIDE';

export const GET_MOVIE_DETAILS          = 'GET_MOVIE_DETAILS';
export const GET_MOVIE_DETAILS_SUCCESS  = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAIL     = 'GET_MOVIE_DETAILS_FAIL';
export const CLEAR_MOVIE_DETAILS        = 'CLEAR_MOVIE_DETAILS';
