export const FETCH_MOVIES_START         = 'FETCH_MOVIES_START';
export const FETCH_NOW_PLAYING_MOVIES   = 'FETCH_NOW_PLAYING_MOVIES';
export const FETCH_NOW_PLAYING_SUCCESS  = 'FETCH_NOW_PLAYING_SUCCESS';
export const FETCH_NOW_PLAYING_FAIL     = 'FETCH_NOW_PLAYING_FAIL';

export const CHANGE_CAROUSEL_MOVIE        = 'CHANGE_CAROUSEL_MOVIE';
export const CHANGE_CAROUSEL_MOVIE_ARROW  = 'CHANGE_CAROUSEL_MOVIE_ARROW';

export const RESIZE_CAROUSEL_SLIDE = 'RESIZE_CAROUSEL_SLIDE';

export const SHOW_MOVIE_DETAILS         = 'SHOW_MOVIE_DETAILS';
export const SHOW_MOVIE_DETAILS_SUCCESS = 'SHOW_MOVIE_DETAILS_SUCCESS';
export const SHOW_MOVIE_DETAILS_FAIL    = 'SHOW_MOVIE_DETAILS_FAIL';
export const CLOSE_MOVIE_DETAILS        = 'CLOSE_MOVIE_DETAILS';
