// RUNS WHEN APPLICATION STARTS
export const FETCH_CONFIG_INIT          = 'FETCH_CONFIG_INIT';
export const FETCH_CONFIG_INIT_START    = 'FETCH_CONFIG_INIT_START';
export const FETCH_CONFIG_INIT_SUCCESS  = 'FETCH_CONFIG_INIT_SUCCESS';
export const FETCH_CONFIG_INIT_FAIL     = 'FETCH_CONFIG_INIT_FAIL';

// RUNS WHEN MOVIES COMPONENT MOUNTS
export const FETCH_MOVIES_START         = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_INIT          = 'FETCH_MOVIES_INIT';
export const FETCH_MOVIES_INIT_SUCCESS  = 'FETCH_MOVIES_INIT_SUCCESS';
export const FETCH_MOVIES_INIT_FAIL     = 'FETCH_MOVIES_INIT_FAIL';

// RUNS WHENEVER MOVIE CAROUSEL CHANGES
export const CHANGE_CAROUSEL_MOVIE        = 'CHANGE_CAROUSEL_MOVIE';
export const CHANGE_CAROUSEL_MOVIE_ARROW  = 'CHANGE_CAROUSEL_MOVIE_ARROW';
export const RESIZE_CAROUSEL_SLIDE        = 'RESIZE_CAROUSEL_SLIDE';

// RUNS WHENEVER CLIENT CLICKS ON A MOVIE
export const GET_MOVIE_DETAILS          = 'GET_MOVIE_DETAILS';
export const GET_MOVIE_DETAILS_SUCCESS  = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAIL     = 'GET_MOVIE_DETAILS_FAIL';
export const CLEAR_MOVIE_DETAILS        = 'CLEAR_MOVIE_DETAILS';
